carto/urls.py
from django.urls import path
from . import views

app_name = 'carto'
urlpatterns = [
    # http://www.auberentransition.fr/carto
    path('', views.index, name='index'),
    # http://www.auberentransition.fr/carto/12
    path('<int:pk>/', views.PoiDetailView.as_view(), name='detail'),
    # http://www.auberentransition.fr/carto/contact
    path('contact/', views.contact, name='contact'),
    # http://www.auberentransition.fr/carto/search
    path('search/', views.search, name='search'),
    path('cours/', views.cours, name='cours'),
    path('test/', views.test, name='test')
]

scrapuloos/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.shortcuts import redirect
import debug_toolbar


def redirect_view(request):
    return redirect('carto:index')


urlpatterns = [
    path('', redirect_view, name='home'),
    path('carto/', include('carto.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('__debug__/', include(debug_toolbar.urls)),
]

carto/models.py
from django.db import models
from django.conf import settings
from mapbox import Geocoder
from django.utils import timezone


class POICategory(models.Model):
    COLOR_CHOICES = (
        ('1', 'Blue'),
        ('2', 'Red'),
        ('3', 'Green'),
        ('4', 'Orange'),
        ('5', 'Yellow'),
        ('6', 'Violet'),
        ('7', 'Grey'),
        ('8', 'Black'),
    )
    label = models.CharField(max_length=250)
    description = models.TextField(blank=True)
    color_id = models.CharField(max_length=1, 
                                choices=COLOR_CHOICES,
                                default='3')
    # poi_set = list of PointOfInterest from foreign key

    def __str__(self):
        return self.label


class PointOfInterest(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField(blank=True)
    address = models.TextField(max_length=400)
    is_localised = models.BooleanField(default=False)
    date_localised = models.DateTimeField(null=True, blank=True)
    addresse_localised = models.TextField(max_length=400, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    geojson_response = models.TextField(blank=True)
    url = models.URLField(null=True, blank=True)
    category = models.ForeignKey(POICategory,
                                 on_delete=models.PROTECT,
                                 related_name='poi_set',
                                 null=True)

    def localise(self, longitude, latitude, address):
        self.is_localised = True
        self.date_localised = timezone.now()
        self.addresse_localised = address
        self.longitude = longitude
        self.latitude = latitude
        self.save()

    def get_coord(self, reverse=False):
        if reverse == False:
            return self.longitude, self.latitude
        else:
            return self.latitude, self.longitude
    
    def __str__(self):
        return self.title

carto/forms.py
from django import forms


class ContactForm(forms.Form):
    email_widget = forms.EmailInput(attrs={'class': 'form-control',
                                           'placeholder': "Votre e-mail"})
    email = forms.EmailField(label='Votre e-mail',
                             max_length=150,
                             widget=email_widget)
    message_widget = forms.Textarea(attrs={'class': 'form-control',
                                           'placeholder': "Votre message",
                                           'rows': '5'})
    message = forms.CharField(label='Votre message',
                              strip=True,
                              widget=message_widget)
                              

carto/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import generic
from django.core.mail import send_mail
from django.views.decorators.http import require_http_methods

from .models import PointOfInterest as POI
from .forms import ContactForm


def cours(request):
    return render(request, 'carto/map.1.html')


def index(request):
    context = {
        'poi_list': POI.objects.filter(is_localised=True),
        'center': (48.915246, 2.394479)
    }
    return render(request, 'carto/map.2.html', context)


@require_http_methods(["POST"])
def search(request):
    slug = request.POST['slug']
    points = POI.objects.filter(is_localised=True) \
                        .filter(title__contains=slug)
    if len(points) > 0:
        long = sum([_.longitude for _ in points]) / len(points)
        lat = sum([_.latitude for _ in points]) / len(points)
    else:
        long, lat = 2.394479, 48.915246
    context = {
        'poi_list': points,
        'center': (lat, long)
    }
    return render(request, 'carto/map.html', context)


class PoiDetailView(generic.DetailView):
    model = POI
    template_name = 'carto/poi_detail.html'


def contact(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)
        if form.is_valid():
            sender = form.cleaned_data['email']
            body = form.cleaned_data['message']
            recipients = ['info@example.com']
            subject = 'Formulaire contact site auberentransition'
            send_mail(subject, body, sender, recipients)
            return render(request, 'carto/contact.html')
    else:
        form = ContactForm()  # blank form
    return render(request, 'carto/contact.html', {'form': form})


def test(request):
    context = {
        'poi_list': POI.objects.filter(is_localised=True)[:10],
        'center': (48.915246, 2.394479)
    }
    return render(request, 'carto/map.2.html', context)

carto/templates/carto/base.html
{% load static %}
<html>
<head>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1,width=device-width">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="theme-color" content="#000000">
<meta name="description" content="">
<meta name="author" content="">

<!-- BOOTSTRAP -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

{% block headleaf %}
{% endblock %}

<!-- APP SPECIFIC -->
<link rel="stylesheet" href="{% static 'carto/css/carto.css' %}" />
</head>
<body>

<!-- NAVBAR -->
<nav class="navbar navbar-expand-md navbar-dark bg-success navbar-fixed-top" role="navigation">
    <a class="navbar-brand" href="#">AuberEnTransition</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'carto:index' %}">Carto<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'carto:contact' %}">Contact</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
      </ul>
      <form action="{% url 'carto:search' %}" class="form-inline my-2 my-md-0" method="POST">
        {% csrf_token %}
        <input name='slug' class="form-control border border-warning" type="text" placeholder="Search">
    </form>
    </div>
  </nav>

{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

carto/templates/carto/contact.html
{% extends "carto/base.html" %}


{% block content %}
<div style="height: 15px;"></div>
<div class="container">
        <div class="row">
            <div class="col-sm">

            </div>
            <div class="col-sm">
                {% if form %}
                <p>N'hésitez pas à nous envoyer un mot d'encouragement :</p>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <p>
                            {{ field.errors }}
                            {{ field }}
                        </p>
                    {% endfor %}
                    <input type="submit" value="Envoyer">
                </form>
                {% else %}
                    <div class="alert alert-success" role="alert">
                        Votre message a été transmis. Merci beaucoup pour votre intérêt.
                    </div>
                {% endif %}
            </div>
            <div class="col-sm poi-actions">
                
            </div>
        </div>
      </div>



{% endblock %}

carto/templates/carto/map.1.html
<html>
<head>
<meta charset="utf-8">
<!-- LEAFLET -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
crossorigin=""/>
<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
crossorigin=""></script>
</head>
<body>
<!-- DIV QUI VA CONTENIR LA CARTE -->
<div id="mapid" style="width: 500px; height: 500px;"></div>
<script>
// Le setView permet de centrer la carte (ici 48.9, 2.4) et de définir le zoom (13)
var mymap = L.map('mapid').setView([48.9, 2.4], 13);
// ici on va chercher le fond de carte et on indique qui le fournit
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(mymap);
// on liste les points que l'on souhaite ajouter
var geojsonFeature = {
    "type": "FeatureCollection",
    "features": [
        { 
            "type": "Feature",
            "properties": {
                "name": "La Villette",
                "popupContent": "cité des sciences et de la villette"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [2.39, 48.9]
            }
        },
        { 
            "type": "Feature",
            "properties": {
                "name": "Pôle emploi",
                "popupContent": "Pensez à vous actualiser"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [2.391, 48.91]
            }
        },
        
    ],
    "attribution": "NOTICE: © 2019 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare."
};

// fonction qui prévient la carte qu'il y a un popup
function onEachFeature(feature, layer) {
    // does this feature have a property named popupContent?
    if (feature.properties && feature.properties.popupContent) {
        layer.bindPopup(feature.properties.popupContent);
    }
}

// on ajoute les points sur la carte en déclenchant le triger
L.geoJSON(geojsonFeature, {
    onEachFeature: onEachFeature
}).addTo(mymap);
</script>
</body>
</html>

carto/templates/carto/map.2.html
{% extends "carto/base.html" %}
{% load static %}

{% block headleaf %}
<!-- LEAFLET -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
crossorigin=""/>
<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
crossorigin=""></script>
<script src="{% static 'carto/js/icons.js' %}"></script>
<script src="{% static 'carto/js/utility.js' %}"></script>
{% endblock %}

{% block content %}
<!-- CARTO -->
<div id="mapid2" class="container-fluid map"></div>
<script>
var mymap = L.map('mapid2').setView([{{ center.0 }}, {{ center.1 }}], 13);

L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(mymap);

{% if poi_list %}

var geojsonFeature = {
    "type": "FeatureCollection",
    "features": [
        {% for poi in poi_list %}
        { 
            "type": "Feature",
            "properties": {
                "name": "{{ poi.title }}",
                "popupContent": "<b><a href='{% url 'carto:detail' poi.id %}'>{{ poi.title }}</a></b><br/>{{ poi.addresse_localised }}",
                {% if poi.category %}
                "icon_color": {{ poi.category.color_id }}
                {% else %}
                "icon_color": 3
                {% endif %}
            },
            "geometry": {
                "type": "Point",
                "coordinates": [{{ poi.longitude }}, {{ poi.latitude }}]
            }
        },
        {% endfor %}
    ],
    "attribution": "NOTICE: © 2019 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare."
};

// See utility.js to find below functions
L.geoJSON(geojsonFeature, {
    onEachFeature: onEachFeature,
    pointToLayer: getMarker 
}).addTo(mymap);

{% endif %}
</script>
{% endblock %}

carto/templates/carto/map.html
{% extends "carto/base.html" %}

{% block headleaf %}
<!-- LEAFLET -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
crossorigin=""/>
<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
crossorigin=""></script>
{% endblock %}

{% block content %}
<!-- CARTO -->
<div id="mapid"></div>
<script>
var mymap = L.map('mapid').setView([{{ center.0 }}, {{ center.1 }}], 13);

L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(mymap);

{% if poi_list %}
function onEachFeature(feature, layer) {
    // does this feature have a property named popupContent?
    if (feature.properties && feature.properties.popupContent) {
        layer.bindPopup(feature.properties.popupContent);
    }
}

var geojsonFeature = {
    "type": "FeatureCollection",
    "features": [
        {% for poi in poi_list %}
        { 
            "type": "Feature",
            "properties": {
                "name": "{{ poi.title }}",
                "popupContent": "<b><a href='{% url 'carto:detail' poi.id %}'>{{ poi.title }}</a></b><br/>{{ poi.addresse_localised }}"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [{{ poi.longitude }}, {{ poi.latitude }}]
            }
        },
        {% endfor %}
    ],
    "attribution": "NOTICE: © 2019 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare."
};
L.geoJSON(geojsonFeature, {
    onEachFeature: onEachFeature
}).addTo(mymap);
{% endif %}
</script>
{% endblock %}

carto/templates/carto/mapbox.html
{% load static %}
<html>
  <head>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css"
    integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
    crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"
    integrity="sha512-QVftwZFqvtRNi0ZyCtsznlKSWOStnDORoefr1enyq5mVL4tmKB3S/EnC3rRJcxCPavG10IcrVGSmPh6Qw5lwrg=="
    crossorigin=""></script>
    
  </head>
  <body>
    <h1>Weather Stations</h1>
    <div id="mapid" style="width: 600px; height: 400px;"></div>
<script>
  function onEachFeature(feature, layer) {
    // does this feature have a property named popupContent?
    if (feature.properties && feature.properties.popupContent) {
        layer.bindPopup(feature.properties.popupContent);
    }
  }

	var mymap = L.map('mapid').setView([2.394479, 48.915246], 13);

	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox.streets',
    accessToken: 'pk.eyJ1Ijoic3dhbm5ibSIsImEiOiJjanN2d2FqOGMwYWZvM3lvMGtvMzVqMnVnIn0.2GI4xpz3Ujy5hZeYtC6-Qw'
  }).addTo(mymap);

  var geojsonFeature = {
    "type": "FeatureCollection",
    "features": [
      { // feature chez moi
        "type": "Feature",
        "properties": {
          "popupContent": "Hello the world ! <a href='{% url 'carto:index' %}'>home</a><p>19 Impasse Du Pont Blanc, <br/>93300 <br/>Aubervilliers, <br/>France</p>"
        },
        "geometry": {
          "type": "Point",
          "coordinates": [
            2.394479,
            48.915246
          ]
        }
      }
    ]
  };

  L.geoJSON(geojsonFeature, {
    onEachFeature: onEachFeature
  }).addTo(mymap);
</script>
  </body>
</html>

carto/templates/carto/poi_detail.html
{% extends "carto/base.html" %}


{% block content %}
<div style="height: 15px;"></div>
<div class="container">
        <div class="row">
            <div class="col-sm">
                <svg class="bd-placeholder-img img-thumbnail img-fluid" width="100%" 
                xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" 
                focusable="false" role="img"><rect width="100%" height="100%" fill="#868e96">
                </rect></svg>
            </div>
            <div class="col-sm">
                <div class="poi">
                    <h1>{{ pointofinterest.title }}</h1>
                    <p>{{ pointofinterest.description | linebreaksbr }}</p>
                    
                    <p>
                        <a href="{{ pointofinterest.url }}" target="_blank">{{ pointofinterest.url }}</a>
                    </p>
                </div>
            </div>
            <div class="col-sm poi-actions">
                Actions:
            </div>
        </div>
      </div>


{% endblock %}